### PR TITLE
Update raptor branch for upstream changes on 2020 branch

### PR DESCRIPTION
**Pull request by marianrai**
As discussed with Henrik, I rebased the raptor branch against the 2020 upstream branch.

What i did for this pull request:
- forked and cloned mozilla's repo
$ git branch raptor remotes/origin/raptor
$ git remote add upstream https://github.com/youtube/js_mse_eme.git
$ git pull upstream
$ git checkout raptor
$ git rebase remotes/upstream/2020
- fixed conflicts
$ git rebase --continue
$ git status
- local raptor branch diverged from origin raptor
- i did a git pull:
$ git pull --allow-unrelated-histories
$ git push -u origin raptor

### CODE REVIEW

**Comment by whimboo** [comment]
@marianrai what is your testing strategy? Do we still have the staging server from Tarek to test those changes on via try in CI? We cannot merge this without having green results across all platforms.

@davehunt is there someone else who could own this repository? I actually shouldn't be the stakeholder here anymore.

**Comment by whimboo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1609373 is the appropriate entry in Bugzilla.

**Comment by marianrai** [comment]
@whimboo 
My strategy is to use a test server where we can fetch this pull request and generate URLs that can be tested in raptor-youtube-playback.ini files through a push to try which will cover all platforms / devices.
I'll talk to Tarek on slack about the staging server. We used that when we investigated the perma failure on Chrome.
Thanks!

**Comment by davehunt** [comment]
> @davehunt is there someone else who could own this repository? I actually shouldn't be the stakeholder here anymore.

I agree, it shouldn't be you. I'm rather limited in my options, but I think it will be best to transfer ownership to @gmierz for now.

**Comment by gmierz** [comment]
@marianrai you will need to apply the upstream changes onto the files inside the 2019 folder. At the moment, they are applied outside of it which is why the test server is still showing the 2019 main page.

A better way might be to create a copy of the 2019 folder, call it 2020, and then rebase all the raptor changes in the 2020 folder onto the upstream 2020 branch changes. There's probably a few other ways to do this as well (giving us one folder per year).

See the wiki for some more info on updating the branches: https://github.com/mozilla/perf-youtube-playback/wiki#download-and-apply-changes

**Review by gmierz — CHANGES_REQUESTED** [review]
See comment above.

**Comment by marianrai** [comment]
This pull request is old and the steps i used to create it are not the right ones, i will close it and create a new one.
Thanks!

**Pull request closed without merging**
